name: Test

on:
  pull_request:

jobs:
  build:
    name: Test ${{ matrix.release }}-${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release:
          - master
          - 24.10.1
          - 23.05.5
        arch:
          - aarch64_generic
          - mips_24kc
          - x86_64
        include:
          - arch: aarch64_generic
            target: armsr/armv8
          - arch: mips_24kc
            target: ath79/generic
          - arch: x86_64
            target: x86/64

    steps:
      - uses: actions/checkout@v4

      - name: Add test directories
        run: mkdir artifacts feed

      - name: Build
        uses: ./
        env:
          TARGET: ${{ matrix.target }}
          VERSION: ${{ matrix.release }}
          ARTIFACTS_DIR: ${{ github.workspace }}/artifacts
          FEED_DIR: ${{ github.workspace }}/feed
          PACKAGES: vim privoxy

      - name: Verify packages saved
        run: find artifacts/bin/packages/${{ matrix.arch }}/packages/ -maxdepth 1 -name '*.[ai]pk' -type f | grep .

      - name: Verify logs saved
        run: find artifacts/logs/package/feeds/packages/ -mindepth 2 -maxdepth 2 -name compile.txt -type f | grep .
